### ISSUE TITLE
Error code 526

### ISSUE THREAD

**Issue by peppercornn1** [evrys/semantle-discord-bot#4]
![IMG_2450](https://github.com/user-attachments/assets/ac65e882-8f2d-4fbe-9dcc-c4fc11d39dc0)

has anyone encountered this error code before, and have a solution?

**Comment by evrys** [comment]
Ah, it's cos the semantle site changed and the HTTPS certificate expired on http://legacy.semantle.com/. I'll see if I can port it to use the new site!

**Comment by evrys** [comment]
Should be fixed now :D
